#SWE 645 Assignment2, Team members:Avinash, Rashi, Rushil, Mithilesh.


#This file create the pods for kubernetes 


apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: swe645/assignment2:dock_img
      ports:
        - containerPort: 8080
