apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  selector:    
    app: nodeapp
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30030
    protocol: TCP
